// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB9yes_VC4zWJhXBn2TI1K8ScMBlDcVdA',
    appId: '1:345192045688:web:e443190e0a1f9a1a2a218d',
    messagingSenderId: '345192045688',
    projectId: 'fir-auth-ae13f',
    authDomain: 'fir-auth-ae13f.firebaseapp.com',
    storageBucket: 'fir-auth-ae13f.appspot.com',
    measurementId: 'G-YR13BT278F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz31L5lvgc0hoPhp7v9FXkMqphiF713LE',
    appId: '1:345192045688:android:301dca64b3d14a122a218d',
    messagingSenderId: '345192045688',
    projectId: 'fir-auth-ae13f',
    storageBucket: 'fir-auth-ae13f.appspot.com',
  );
}
